// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vid2.Blog.Api.Data;

#nullable disable

namespace Vid2.Blog.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vid2.Blog.Api.Models.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompletionResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("completion_result");

                    b.Property<string>("YoutubeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("youtube_id");

                    b.HasKey("Id")
                        .HasName("pk_results");

                    b.HasIndex("YoutubeId")
                        .IsUnique()
                        .HasDatabaseName("ix_results_youtube_id");

                    b.ToTable("results", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
